name: attendance
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0



  intl: ^0.17.0
#  es_drawer_controller: ^1.0.8
#  fab_circular_menu: ^1.0.0
  persian_datetime_picker:
    path: edit_packages/persian_datetime_picker-2.3.0
  lottie: ^1.2.1
  flutter_countdown_timer: ^4.1.0
  stacked: ^2.2.5
  logger: ^1.0.0
  image_picker: ^0.8.4+3
#  flutter_slider_drawer: ^2.0.0

  #  image_cropper: ^1.4.1
  page_transition: ^2.0.4
  line_icons: ^2.0.1
  #  geolocator: ^8.0.0
#  geocoding: ^2.0.1
  shared_preferences: ^2.0.8
  stacked_services: ^0.8.13
#  flutter_lints: ^1.0.0
  flutter_svg: ^1.0.0
  dio: ^4.0.0
  pin_code_fields: ^7.3.0
#  firebase_core: ^1.7.0
  simple_animations: ^4.0.1
  json_annotation: ^4.3.0
  flutter_easyloading: ^3.0.3
  cached_network_image: ^3.1.0
  injectable:
  google_fonts: ^2.1.0
  fluttertoast: ^8.0.8
#  jalali_calendar: ^1.0.4
#  day_night_time_picker: ^1.0.3+1
  cupertino_icons: ^1.0.2
  internet_connection_checker: ^0.0.1+3
#  desktop_window: ^0.4.0
#  window_size:
#    git:
#      url: git://github.com/google/flutter-desktop-embedding.git
#      path: plugins/window_size

#  firebase_analytics: ^9.0.4



dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints: ^1.0.0
  stacked_generator: ^0.5.2
  injectable_generator:
  auto_route_generator: ^3.2.0
  build_runner:
  moor_generator:
  json_serializable: ^6.0.0


flutter:




  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: vazir
      fonts:
        - asset: fonts/vazir_thin.ttf
          weight: 300
        - asset: fonts/vazir_light.ttf
          weight: 400
        - asset: fonts/vazir_regular.ttf
          weight: 500
        - asset: fonts/vazir_medium.ttf
          weight: 600
        - asset: fonts/vazir_bold.ttf
          weight: 700
